/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'genji' at '11/28/16 5:51 PM' with Gradle 2.14.1
 *
 * @author genji, @date 11/28/16 5:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
