/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'genji' at '1/4/16 12:13 PM' with Gradle 2.8
 *
 * @author genji, @date 1/4/16 12:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
