/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'genji' at '1/2/16 5:24 PM' with Gradle 2.8
 *
 * @author genji, @date 1/2/16 5:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
