- JavaFXHelloWorld.java: contiene il codice basic (senza XML importato)
- GUI.fxml: costruito con Scene Builder 
- GUIController.java: il controller (gestione degli eventi della GUI)  
- SceneBuilderHelloWorld.java: l'applicazione
